export const loaderPageStates = {
  IS_LOADING: 'IS_LOADING',
  COMPLETED_LOADING: 'COMPLETED_LOADING',
  SHOW_INTRO: 'SHOW_INTRO',
  ANIMATE_PAGE_REVEAL: 'ANIMATE_PAGE_REVEAL',
  SHOW_PAGE: 'SHOW_PAGE',
}